workspace:
  base: /home/gradle
  path: /
pipeline:
  build:
    image: gradle:4.4-jdk8-alpine
    pull: true
    commands:
      - gradle clean
      - gradle assemble
  test:
    image: jonasfranz/gradle-with-firefox:4.4-jdk8-alpine
    pull: true
    commands:
      - gradle :jvm:test #JavaScript tests are currently corrupted
  deploy:
    image: gradle:4.4-jdk8-alpine
    pull: true
    secrets: [ BINTRAY_API_KEY, BINTRAY_USER]
    commands:
      - gradle publish
    when:
      event: [ tag ]
  github_release:
    image: plugins/github-release
    secrets: [ github_token ]
    files:
      - common/build/libs/*
      - jvm/build/libs/*
      - js/build/libs/*
    checksum:
      - md5
      - sha1
      - sha512
    when:
      event: tag
