workspace:
  base: /home/gradle
  path: /
pipeline:
  build_and_test:
    image: jonasfranz/openjdk-with-firefox:8-jdk
    pull: true
    commands:
      - ./gradlew clean
      - ./gradlew assemble
      - ./gradlew :jvm:test
  deploy:
    image: openjdk:8-jdk
    pull: true
    secrets: [ bintray_api_key, bintray_user ]
    commands:
      - ./gradlew bintrayUpload
    when:
      event: [ tag ]
  github_release:
    image: plugins/github-release
    secrets: [ github_token ]
    files:
      - common/build/libs/*
      - jvm/build/libs/*
      - js/build/libs/*
    checksum:
      - md5
      - sha1
      - sha512
    when:
      event: tag
